spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    poolName: hikariPCpool
    connection-test-query: select 1 from dual
    hikari:
        connection-timeout: 30000
        idle-timeout: 10000
        max-lifetime: 1800000
        maximum-pool-size: 10
        autoCommit: false
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lht_test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 198412

  kafka:
    #    bootstrap-servers: 53.80.6.45:9092,53.80.6.46:9092,53.80.6.47:9092,53.80.6.48:9092
    #    bootstrap-servers: 10.4.106.21:9092,10.4.106.22:9092,10.4.106.23:9092,10.4.106.24:9092
    consumer:
      bootstrap-servers: 10.4.106.21:9092,10.4.106.22:9092,10.4.106.23:9092,10.4.106.24:9092
      enable-auto-commit: true
      auto-commit-interval: 1
      auto-offset-reset: latest
      group-id: warning_group_1
    producer:
      #      servers: 53.80.6.45:9092,53.80.6.46:9092,53.80.6.47:9092,53.80.6.48:9092
      #      servers: 10.4.106.21:9092,10.4.106.22:9092,10.4.106.23:9092,10.4.106.24:9092
      bootstrap-servers: 10.4.106.21:9092,10.4.106.22:9092,10.4.106.23:9092,10.4.106.24:9092
      topic: warning_new1
      acks: all
      retries: 0
      batch-size: 4096
      buffer-memory: 40960
      linger: 1
      client-id: messageTest




#server:
#  tomcat:
##  max-http-header-size: 655360
#  port: 9090

mybatis:
    mapper-locations: classpath:mapper/*.xml
    config-location: classpath:mapper/mybatisConfig/mybatisConfig.xml

interceptor:
  test:
    urls:
      -  "/interceptor/*"

filter:
  test:
    urls:
    -  "/filter/*"
    -  "/interceptor/*"



