spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    poolName: hikariPCpool
    connection-test-query: select 1 from dual
    hikari:
        connection-timeout: 30000
        idle-timeout: 10000
        max-lifetime: 1800000
        maximum-pool-size: 10
        autoCommit: false
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lht_test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 198412

  kafka:
    consumer:
      bootstrap-servers: 10.4.106.21:9092,10.4.106.22:9092,10.4.106.23:9092,10.4.106.24:9092
      enable-auto-commit: true
      auto-commit-interval: 1
      auto-offset-reset: latest
      group-id: warning_group_1
    producer:
      bootstrap-servers: 10.4.136.87:9092,10.4.136.87:19092,110.4.136.87:9092
      topic: warning_new1
      acks: all
      retries: 0
      batch-size: 4096
      buffer-memory: 40960
      linger: 1
      client-id: messageTest


  redis:
    host: 10.4.106.7
    timeout: 3000
    password:
    port: 16379
    database: 5
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制)
        min-idle: 0 # 连接池中的最小空闲连接




#server:
#  tomcat:
##  max-http-header-size: 655360
#  port: 9090

mybatis:
    mapper-locations: classpath:mapper/*.xml
    config-location: classpath:mapper/mybatisConfig/mybatisConfig.xml

interceptor:
  test:
    urls:
      -  "/interceptor/*"

filter:
  test:
    urls:
    -  "/filter/*"
    -  "/interceptor/*"



